### ISSUE TITLE
Associate price ID to cart items

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-cart#14]
When a booking cart item is added to the EDD cart, the `price_id` should ideally be set.

This allows other parts of EDD, such as the payment details page, to show the price option. Otherwise, the purchased booking may be shown as follows instead:

```
My Service - 
```

This can be observed in the EDD payment details page as well as the purchase confirmation page under the **Products** section. The price option name should follow the dash. This is, of course, not ideal.

**Comment by markzahra** [comment]
I cannot yet test this change in Alpha 11 due to the unrelated bug causing the available sessions to not be shown in the Nedit Booking modal or the Booking Wizard. I will test again in Alpha 12.
